# https://travis-ci.community/t/error-installing-oraclejdk8-expected-feature-release-number-in-range-of-9-to-14-but-got-8/3766/4
dist: trusty

language: java
jdk: oraclejdk8

install:
- mvn clean package -Dcheckstyle.skip=true

test:
- mvn test -B -Dcheckstyle.skip=true

after_success:
- mvn coveralls:report
